server:
  port: 8416

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-admin-mvc?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 12345678
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      idle-timeout: 3000
      max-lifetime: 50000

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

